---
# tasks file for roles/jerveclark.jenkins-docker
- name: Ensure dependencies are installed
  apt:
    name:
      - python3-pip
      - unzip
    state: present

- name: Ensure docker module is installed
  pip:
    name: docker
    state: present

- name: Pull latest jenkins image
  docker_image:
    name: jenkinsci/blueocean
    tag: latest
    state: present

- name: Create jenkins_home directory
  file:
    path: /home/vagrant/jenkins_home
    owner: vagrant
    group: vagrant
    state: directory

- name: Run jenkins container
  docker_container:
    name: jenkins
    image: jenkinsci/blueocean:latest
    ports:
      - 1317:8080
      - 50000:50000
    volumes:
      - /home/vagrant/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    state: started
    privileged: true
  register: jenkins_container

- name: Copy jenkins setup
  unarchive:
    src: ../artifacts/jenkins_home.zip
    dest: /home/vagrant/
    keep_newer: true
    owner: vagrant
    group: vagrant
  when: jenkins_container.changed

# TO-DO: remove this task because of security reasons
- name: Change docker.sock permission
  file:
    path: /var/run/docker.sock
    mode: 0777
